### ISSUE TITLE
Руководство пользователя по РДО

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#26]
- [x] Как скачать РДО
  - [x] [Эклипс скачивается с нашего сайта как архив, уже с плагином](https://github.com/aurusov/rdo-xtext/issues/26#issuecomment-139803565)
  - [x] [Эклипс с офф. сайта, плагин доставляется руками](https://github.com/LeKaitoW/rdo-xtext/issues/22#issuecomment-135145683)
- [ ] Как обновить уже установленный РДО (так же, как [Эклипс с офф. сайта, плагин доставляется руками](https://github.com/LeKaitoW/rdo-xtext/issues/22#issuecomment-135145683))
- [x] Как [импортировать](https://github.com/aurusov/rdo-xtext/issues/26#issuecomment-140819434) существующую модель
- [x] Как [создать новую](https://github.com/aurusov/rdo-xtext/issues/26#issuecomment-140745480)

**Comment by LeKaitoW** [comment]
Перенесу из lekaitow/rdo-xtext#22:

Эклипс скачивается с нашего сайта как архив, уже с плагином:
- Download Eclipse
- Run Eclipse
- `Window` > `Open Perspective` > `Other` > `RDO`

Эклипс с офф. сайта, плагин доставляется руками:
- Download Eclipse
- Download RDO in `.../eclipse/dropins`
- Run Eclipse
- `Window` > `Open Perspective` > `Other` > `RDO`

Эклипс с плагином, но пользователь хочет обновить РДО руками:
- Download Eclipse
- Download (new) RDO and replace in `.../eclipse/dropins`
- Run Eclipse
- `Window` > `Open Perspective` > `Other` > `RDO`

Импортировать существующую модель:

Создание новой модели:

**Comment by aurusov** [comment]
## Эклипс скачивается с нашего сайта как архив, уже с плагином
- Download Eclipse
- Run Eclipse
- `Window` > `Open Perspective` > `Other` > `Rao`

**Comment by aurusov** [comment]
Оля, напиши инструкцию по двум последним пунктам
- Как импортировать существующую модель
- Как создать новую (на русском)

**Comment by aurusov** [comment]
@LeKaitoW 
Пингую, посмотри пред. сообщение.

**Comment by LeKaitoW** [comment]
> Как импортировать существующую модель

Имеется в виду копипаста из файла в файл? Или что?

**Comment by aurusov** [comment]
> Имеется в виду копипаста из файла в файл? Или что?

Да. Но только думай пользователем, который открыл пустое РДО. Т.е. сначала надо создать модель, потом на гибхаб за моделью, потом копипаста.

> Создать новую

Описания сильно отличаются, а был нужен только перевод. Надо
- или перевести весь раздел Running
- или почистить его, если он упростился после визарда

**Comment by LeKaitoW** [comment]
> или почистить его, если он упростился после визарда

Уже обновила ридми в ветке визарда.

**Comment by aurusov** [comment]
> Уже обновила ридми в ветке визарда.

Увидел. Отличаются строчкой про перспективу.

**Comment by LeKaitoW** [comment]
> Увидел. Отличаются строчкой про перспективу.

Так вроде так и должно быть. Что-то исправить в этой инструкции нужно или нет?

**Comment by aurusov** [comment]
Хорошо, можно без перспективы. Переношу в отдельное сообщение

**Comment by aurusov** [comment]
## Создать новую
- `File` > `New` > `Project...` > `Rao` > `Rao Project` > `Next` > `Project name:` 
  - ввести имя проекта
  - выбрать шаблон модели
- `Finish`

**Comment by LeKaitoW** [comment]
## Импортировать существующую модель
- `File` > `New` > `Project...` > `Rao` > `Rao Project` > `Next` > `Project name:` 
  - ввести имя проекта
  - выбрать шаблон "Пустая модель"
- `Finish`
- Скопировать текст [модели](https://github.com/aurusov/rdo-xtext-models) в файл `*.rao`

**Comment by aurusov** [comment]
Хорошо. Теперь подумаю как это оформить для студентов. Переключаю задачу на себя.

**Comment by aurusov** [comment]
Прошу досмотреть. Документация сейчас невалидна из-за https://github.com/aurusov/rdo-xtext/issues/189. Если не получится запустить модель, то буду как-то переделывать.
