### ISSUE TITLE
Релиз RAO-XT к учебному году

### ISSUE THREAD

**Issue by bogachev-pa** [LeKaitoW/raox#48]
@aurusov, @k-alexandrovsky, @LeKaitoW, @kstrizhov

Метатаска для обсуждения задач, которые необходимы для релиза РДО.
##### Для пользователей (студентов)
- [x] [Новая грамматика](https://github.com/aurusov/rdo-xtext/pull/45) (@bogachev-pa)
- [x] [Документация по новой грамматике](https://github.com/bogachev-pa/rdo-xtext/issues/24) (@bogachev-pa)
- [ ] [Масштабирование графа](https://github.com/aurusov/rdo-xtext/issues/150) (@bogachev-pa)
- [ ] [Руководство пользователя](https://github.com/aurusov/rdo-xtext/issues/26) (@LeKaitoW)
- [ ] [Плагин пятнашек](https://github.com/aurusov/rdo-xtext/issues/52) (@LeKaitoW)
- [ ] [Визард создания моделей](https://github.com/aurusov/rdo-xtext/issues/53) (@LeKaitoW)
##### Для разработчиков (рефакторинг лучше всего делать между сессиями)
- [x] [Инструкция для подготовки бинарного релиза РДО](https://github.com/LeKaitoW/rdo-xtext/issues/22) (@LeKaitoW)
- [x] [Чистка кода в проекте кодогенерации](https://github.com/bogachev-pa/rdo-xtext/issues/32) (@bogachev-pa)
- [x] [Реорганизовать файлы проектов](https://github.com/bogachev-pa/rdo-xtext/issues/27) (@bogachev-pa)
- [x] [Убрать префикс `RDO` у всех классов проекта](https://github.com/bogachev-pa/rdo-xtext/issues/33) (@bogachev-pa)
- [x] [Унифицировать схему нотификации гуи об изменениях в базе данных](https://github.com/bogachev-pa/rdo-xtext/issues/30) (@bogachev-pa)
- [ ] [Навести порядок в способах хранения структуры модели](https://github.com/bogachev-pa/rdo-xtext/issues/29) (@bogachev-pa)
- [x] [Выбрасывать исключения вместо возврата null'ов в случае внутренних ошибок](https://github.com/bogachev-pa/rdo-xtext/issues/28) (@bogachev-pa)
##### Для пользователей (студентов)
- [ ] [У графиков не появляются ползунки прокрутки](https://github.com/aurusov/rdo-xtext/issues/49) (@aurusov)
- [ ] [Перемещение по графику вправо-влево через колёсо мышки](https://github.com/aurusov/rdo-xtext/issues/50) (@aurusov)
- [ ] [Масштабирование графика через колёсо мышки](https://github.com/aurusov/rdo-xtext/issues/51) (@aurusov)
- [x] [Автоматический выбор действия над объектом](https://github.com/aurusov/rdo-xtext/issues/55) (@aurusov)
- [x] [Исправить отображение трассировки под Windows](https://github.com/bogachev-pa/rdo-xtext/issues/26) (@bogachev-pa)
- [ ] [В режиме без анимации отображается начало трассировки](https://github.com/bogachev-pa/rdo-xtext/issues/23) (@bogachev-pa)
- [ ] [Исправить tab order в окне поиска по трассировке](https://github.com/bogachev-pa/rdo-xtext/issues/19) (@bogachev-pa)
- [ ] [Сохранять конфигурацию traceConfig после перезапуска eclipse](https://github.com/bogachev-pa/rdo-xtext/issues/17) (@bogachev-pa)
- [ ] [Графики для одного и того же момента времени](https://github.com/aurusov/rdo-xtext/issues/60)
- [ ] [График из одной точки](https://github.com/aurusov/rdo-xtext/issues/61)
##### Для разработчиков
- [ ] [Поднять систему тестирования](https://github.com/aurusov/rdo-xtext/issues/54)

Дополняйте

**Comment by aurusov** [comment]
Выглядит полным. Систему тестирования очень хочется, но я бы вынес её за скобки.

**Comment by aurusov** [comment]
Попробоуйте в своих тасках прописать ссылку на milestone `RAO-XT к учебному году`. В ваших форках гитхаб мне предлагаю создать новый milestone.

**Comment by bogachev-pa** [comment]
Milestone между форками не шарится, я так понимаю.

**Comment by aurusov** [comment]
Печалька, прям хоть заводи задачи-прокси, как эта.

**Comment by bogachev-pa** [comment]
Но мне кажется, вы по крайней мере можете поставить их на пул-реквесты.

**Comment by aurusov** [comment]
Ага, хоть что-то. Почему-то не могу тебя назначать отвественным на задачи.

**Comment by aurusov** [comment]
Сделал тебя колаборатором, теперь могу.

**Comment by aurusov** [comment]
Закрываю, т.к. топик уже состоялся. Постарался вытащить самое важно и незаконченное в два других раздела
- [К первой лабе](https://github.com/aurusov/rdo-xtext/milestones/%D0%9A%20%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%B9%20%D0%BB%D0%B0%D0%B1%D0%B5)
- [Ко второй лабе](https://github.com/aurusov/rdo-xtext/milestones/%D0%9A%D0%BE%20%D0%B2%D1%82%D0%BE%D1%80%D0%BE%D0%B9%20%D0%BB%D0%B0%D0%B1%D0%B5)
